### ISSUE TITLE
  Cell Segmentation问题，tissue cut有遗漏以及 有多余的细胞被分割出来

### ISSUE THREAD

**Issue by easyc1** [BGIResearch/stereopy#101]
执行代码
from stereo import image as im
im.cell_seg(model_path, img_path, out_path)

1、原始数据内有6个tissue，只cut出5个tissue
<img width="640" alt="image" src="https://user-images.githubusercontent.com/52228192/222082038-48a529c4-6324-4e3f-ae8d-dd03b1037ca2.png">

2、分割的结果中出现了原始tif上并没有的信号（红框圈出来的）
![image](https://user-images.githubusercontent.com/52228192/222083058-dd142b85-1e7f-4499-b9c3-13ffd9e9ae0f.png)

**Comment by easyc1** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/52228192/222419096-fd500d3b-9cda-4cd0-95ed-9543f29d0998.png">
还有个问题，细胞分割的结果跟原始数据比中间有很多空的区域

**Comment by TheSallyGardens** [comment]
Stereopy will update the algorithm to solve this problem in subsequent versions. If you have similar problems, please visit https://www.stomics.tech/sap/home.html contact us.
