### ISSUE TITLE
error: cgef to h5ad

### ISSUE THREAD

**Issue by zt6597** [BGIResearch/stereopy#102]
Hi stereopy teams!
I have generated cellbin.cgef and i want to convert to h5ad format, yet i got the error: [reader][429][ERROR]: convert to AnnData should have raw data. the code was: 
path_high_res = "./data/nom_1d_highres_cellbin.gef"
data_high_res = st.io.read_gef(path_high_res, bin_type='cell_bins')
data_high_res.tl.cal_qc()
ins_high_res = data_high_res.plt.interact_spatial_scatter(width=500, height=500, poly_select=True)
ins_high_res.show()
adata = st.io.stereo_to_anndata(data_high_res,flavor='scanpy',output='nom_1d_highres_cellbin.h5ad')

TRACEBACK:
[2023-03-01 16:32:21][Stereo][14329][140019443029824][reader][429][ERROR]: convert to AnnData should have raw data
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 adata = st.io.stereo_to_anndata(data_high_res,flavor='scanpy',output='nom_1d_highres_cellbin.h5ad')

File ~/miniconda3/envs/st/lib/python3.8/site-packages/stereo/io/reader.py:430, in stereo_to_anndata(data, flavor, sample_id, reindex, output, split_batches)
    428 if data.tl.raw is None:
    429     logger.error('convert to AnnData should have raw data')
--> 430     raise Exception
    432 exp = data.tl.raw.exp_matrix if issparse(data.tl.raw.exp_matrix) else csr_matrix(data.tl.raw.exp_matrix)
    433 cells = data.tl.raw.cells.to_df()

Exception: 

**Can you check this error, many thanks!**

**Comment by tanliwei-coder** [comment]
Please running the `data_high_res.tl.raw_checkpoint()` after `data_high_res.tl.cal_qc()` to save the raw data.

**Comment by zt6597** [comment]
thanks!
