### ISSUE TITLE
Not able to use stereopy after installation 

### ISSUE THREAD

**Issue by pratapstat** [BGIResearch/stereopy#103]
I have followed instructions from stereopy instructions page through the following link (https://stereopy.readthedocs.io/en/latest/General/Installation.html) by typing the following commands
conda create --name st python=3.8
conda activate st
pip install stereopy

After installation, when I was trying to use stereopy by typing the following commands ( shown below) it's giving an error.
import warnings
warnings.filterwarnings('ignore')
import stereo as st

It would be really helpful, if you help on this.

**Comment by TheSallyGardens** [comment]
@pratapstat  Hi!
Could you show the error message?

**Comment by pratapstat** [comment]
@TheSallyGardens 
Hi, I'm using my mac (mac os: Ventura 13.2.1) and  the error message is shown below


ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 import stereo as st

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/stereo/__init__.py:10
      8 from . import tools
      9 from . import utils
---> 10 from . import plots as plt
     11 from . import image

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/stereo/plots/__init__.py:13
     11 from .marker_genes import marker_genes_text, marker_genes_heatmap
     12 from .plot_collection import PlotCollection
---> 13 from .interact_plot.spatial_cluster import interact_spatial_cluster
     14 from .interact_plot.interactive_scatter import InteractiveScatter
     15 from .interact_plot.poly_selection import PolySelection

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/stereo/plots/interact_plot/spatial_cluster.py:8
      1 #!/usr/bin/env python3
      2 # coding: utf-8
      3 """
      4 @author: qindanhua@genomics.cn
      5 @time:2021/09/06
      6 """
----> 8 import holoviews as hv
      9 import hvplot.pandas
     10 import panel as pn

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/holoviews/__init__.py:12
      8 __version__ = str(param.version.Version(fpath=__file__, archive_commit="$Format:%h$",
      9                                         reponame="holoviews"))
     11 from . import util                                       # noqa (API import)
---> 12 from .annotators import annotate                         # noqa (API import)
     13 from .core import archive, config                        # noqa (API import)
     14 from .core.boundingregion import BoundingBox             # noqa (API import)

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/holoviews/annotators.py:10
      6 from inspect import getmro
      8 import param
---> 10 from panel.pane import PaneBase
     11 from panel.layout import Row, Tabs
     12 from panel.util import param_name

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/panel/__init__.py:1
----> 1 from . import layout # noqa
      2 from . import links # noqa
      3 from . import pane # noqa

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/panel/layout/__init__.py:1
----> 1 from .accordion import Accordion # noqa
      2 from .base import Column, ListLike, ListPanel, Panel, Row, WidgetBox # noqa
      3 from .card import Card # noqa

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/panel/layout/accordion.py:5
      1 import param
      3 from bokeh.models import Column as BkColumn, CustomJS
----> 5 from .base import NamedListPanel
      6 from .card import Card
      9 class Accordion(NamedListPanel):

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/panel/layout/base.py:11
      7 import param
      9 from bokeh.models import Column as BkColumn, Row as BkRow
---> 11 from ..io.model import hold
     12 from ..io.state import state
     13 from ..reactive import Reactive

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/panel/io/__init__.py:9
      6 import logging
      7 import sys
----> 9 from ..config import config
     11 from .callbacks import PeriodicCallback # noqa
     12 from .embed import embed_state # noqa

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/panel/config.py:20
     14 import param
     16 from pyviz_comms import (
     17     JupyterCommManager as _JupyterCommManager, extension as _pyviz_extension
     18 )
---> 20 from .io.notebook import load_notebook
     21 from .io.state import state
     23 __version__ = str(param.version.Version(
     24     fpath=__file__, archive_commit="$Format:%h$", reponame="panel"))

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/panel/io/notebook.py:14
     11 from six import string_types
     13 import bokeh
---> 14 import bokeh.embed.notebook
     16 from bokeh.core.json_encoder import serialize_json
     17 from bokeh.core.templates import MACROS

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/bokeh/embed/__init__.py:23
     16 log = logging.getLogger(__name__)
     18 #-----------------------------------------------------------------------------
     19 # Imports
     20 #-----------------------------------------------------------------------------
     21 
     22 # Bokeh imports
---> 23 from .server import server_document, server_session
     24 from .standalone import autoload_static, components, file_html, json_item
     26 #-----------------------------------------------------------------------------
     27 # Globals and constants
     28 #-----------------------------------------------------------------------------

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/bokeh/embed/server.py:25
     22 from urllib.parse import quote_plus, urlparse
     24 # Bokeh imports
---> 25 from ..core.templates import AUTOLOAD_REQUEST_TAG, FILE
     26 from ..resources import DEFAULT_SERVER_HTTP_URL
     27 from ..util.serialization import make_id

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/bokeh/core/templates.py:41
     38 from os.path import dirname, join
     40 # External imports
---> 41 from jinja2 import Environment, FileSystemLoader
     43 #-----------------------------------------------------------------------------
     44 # Globals and constants
     45 #-----------------------------------------------------------------------------
     47 __all__ = (
     48     'AUTOLOAD_JS',
     49     'AUTOLOAD_NB_JS',
   (...)
     62     'SCRIPT_TAG',
     63 )

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/jinja2/__init__.py:12
     10 from .bccache import FileSystemBytecodeCache
     11 from .bccache import MemcachedBytecodeCache
---> 12 from .environment import Environment
     13 from .environment import Template
     14 from .exceptions import TemplateAssertionError

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/jinja2/environment.py:25
     23 from .compiler import CodeGenerator
     24 from .compiler import generate
---> 25 from .defaults import BLOCK_END_STRING
     26 from .defaults import BLOCK_START_STRING
     27 from .defaults import COMMENT_END_STRING

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/jinja2/defaults.py:3
      1 # -*- coding: utf-8 -*-
      2 from ._compat import range_type
----> 3 from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
      4 from .tests import TESTS as DEFAULT_TESTS  # noqa: F401
      5 from .utils import Cycler

File ~/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/jinja2/filters.py:13
     11 from markupsafe import escape
     12 from markupsafe import Markup
---> 13 from markupsafe import soft_unicode
     15 from ._compat import abc
     16 from ._compat import imap

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/Users/pratap/opt/anaconda3/envs/stereo_py/lib/python3.8/site-packages/markupsafe/__init__.py)

**Comment by TheSallyGardens** [comment]
@pratapstat  Hi!
Sorry, Stereopy does not support the mac system at present.

**Comment by pratapstat** [comment]
@TheSallyGardens thanks. Is there any docker or container available for mac ?

**Comment by TheSallyGardens** [comment]
Currently, it supports linux and window, and plans to support mac in the future.

**Comment by junhouhui** [comment]
hi，we already push the stereopy (version: 0.6.0) image to Dockerhub, please visit [stereopy_docker](https://hub.docker.com/repository/docker/stomics/stereopy)

**Comment by junhouhui** [comment]
docker execute command:
docker run -p 8888:8888 -it bgi-research/stereopy:1.0 /bin/bash -c "jupyter lab --JupyterApp.config_file='/home/stereonote/jupyter_notebook_config.py' --allow-root --ip=0.0.0.0 --NotebookApp.passwd=''"

**Comment by junhouhui** [comment]
Notice: this issue has been closed because it has been inactive for 14 days. You may reopen this issue if it has been closed in error.
