### ISSUE TITLE
data_helper.merge merge slices

### ISSUE THREAD

**Issue by JingGuo1997** [BGIResearch/stereopy#104]
Hello, Stereopy team,

When I use the data_helper.merge function to merge two slices and save them as an anndata file using st.io.stereo_to_anndata(data, flavor='scanpy'......), two files are generated .But i want get only one merged file.

I am  looking  forward to your response.

Sincerely

**Comment by tanliwei-coder** [comment]
Hi

please set the parameter `split_batches` to False.
