### ISSUE TITLE
marker gene plot 

### ISSUE THREAD

**Issue by xiangyugits** [BGIResearch/stereopy#105]
Hello, Stereopy team：

How can I visualize single gene like seurat SpatialFeaturePlot?

Sincerely

**Comment by tanliwei-coder** [comment]
Hi !!

You can run the method `data.plt.spatial_scatter_by_gene(gene_name='xxx')`, specify the gene you want to plot by parameter `gene_name`.

**Comment by junhouhui** [comment]
Notice: this issue has been closed because it has been inactive for 14 days. You may reopen this issue if it has been closed in error.
