### ISSUE TITLE
交互式不起作用

### ISSUE THREAD

**Issue by lvmt** [BGIResearch/stereopy#107]
你好，我按照教程代码运行交互式截取感兴趣区域，但是界面没有显示。
```
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')
import stereo as st
import  os  
os.chdir('C:/Users/llmt/Desktop/jupyter  notebook')
path = 'data/demo/SS200000135TL_D1.tissue.gef'
data = st.io.read_gef(path, bin_size=40)
data.tl.cal_qc()
ins = data.plt.interact_spatial_scatter(width=500, height=500, poly_select=False)
ins.show()
```
![image](https://user-images.githubusercontent.com/34225000/228702895-a11565cb-2a52-4b4c-80ae-fb3e7b3b0084.png)

**Comment by TheSallyGardens** [comment]
Are you using windows? 
Please run pip list and provide us your software version information.

**Comment by TheSallyGardens** [comment]
@lvmt  Hi.
If you cannot use the Linux environment, you can temporarily install WSL2 on Windows. We will notify you when we solve this problem

**Comment by lvmt** [comment]
hi, i have updated stereopy to 0.11.0 , now it work good.  thanks for your work.
