### ISSUE TITLE
How to draw the ssDNA image?

### ISSUE THREAD

**Issue by vagabond12** [BGIResearch/stereopy#114]
You have told how to draw the ssDNA image in the tutorial as indicated below.

![image](https://user-images.githubusercontent.com/24886447/233365225-e2618e80-c270-4c61-a591-367b480d5f73.png)

However, we could not realize it as indicated below. So why?

![image](https://user-images.githubusercontent.com/24886447/233365564-a162a866-f1cc-438d-ab7f-af4e1af8a599.png)

And we do not know where to download the tutorial data.

Could you help us? Thank you.

**Comment by junhouhui** [comment]
Hi, you can download our tutorial data through [this link](https://pan.genomics.cn/ucdisk/s/BvIrye)
Regarding the issue with images not displaying, could you please clear your browser cache and then try running it again?

**Comment by junhouhui** [comment]
Notice: this issue has been closed because it has been inactive for 14 days. You may reopen this issue if it has been closed in error.
