### ISSUE TITLE
How to draw nGene on umap

### ISSUE THREAD

**Issue by ZeroLi-Bio** [BGIResearch/stereopy#117]
Hello developers,
I want to draw the nGene and nCounts on the umap scatter plot, I tried using:
`data.plt.umap(cluster_key='n_genes_by_counts', res_key='umap')
data.plt.umap(cluster_key='n_counts', res_key='umap')`
But they didnt work. Is there a function to do this? 

Thank you so much!

**Comment by junhouhui** [comment]
Hello, i am sorry, but data.plt.umap function currently doesn't support plotting nGene and nCounts expressiond on Umap plots.

**Comment by junhouhui** [comment]
Notice: this issue has been closed because it has been inactive for 14 days. You may reopen this issue if it has been closed in error.
