### ISSUE TITLE
plt.marker_genes_scatter cannot plot using scaled data

### ISSUE THREAD

**Issue by ZeroLi-Bio** [BGIResearch/stereopy#118]
Hello,
When I tried to make the DEGs dotplot, I found stereopy cannot plot using the scaled data but only the raw counts(by default). It made the differentially expressed genes not obvious from the plot.(same in the tutorial "Quick Start")

Besides, I coundn't find an introduction about the "plt.marker_genes_scatter" function in API pages of [stereopy.readthedocs.io](url). So i checked the source codes of it and it seems doesn't include this option/feature indeed.[https://github.com/BGIResearch/stereopy/blob/bc7b3a29e3c28d5f2d62d3192736872955b52960/stereo/plots/plot_collection.py](url)

Hope you could consider add this because it's a commonly used plotting method in scanpy and seurat.

Thanks

**Comment by tanliwei-coder** [comment]
Hi,
I'm so sorry to tell you, it just only can plot based on raw counts by default currently.

And, could you tell me how to deal with negative values if plotting based on scaled data.

**Comment by ZeroLi-Bio** [comment]
I don't understand what do you mean about the negative values. This is plotted by Seurat and it includes negative values.
![image](https://github.com/BGIResearch/stereopy/assets/48876554/085ee454-0628-44d0-a3a3-6eec1e39a4ab)

**Comment by tanliwei-coder** [comment]
Thanks! We will update to support this feature.

**Comment by Zjianglin** [comment]
Hi @tanliwei-coder , is this problem solved yet? 

I want to analyze multiple slices/samples using `stereopy`. Now, I followed the [Batch_Effect](https://stereopy.readthedocs.io/en/latest/Tutorials%28Multi-sample%29/Batch_Effect.html) tutorial, is it right? Should I treat the results of `batches_integrate`  as the batch effect removed such as `integrated` assay in `Seurat`?

What values does the `marker_genes_scatter` function use to plot gene expression, and how should it be set to use normalized expression values? Furthermore, if a gene is not a DEG (and may not be in the resulting `'marker_genes'` of `find_marker_genes`) , how do you map its expression profile in this case? Thanks
