### ISSUE TITLE
Conversion of GEM and GEF file formats

### ISSUE THREAD

**Issue by Taoli0113** [BGIResearch/stereopy#121]
Hello, how can I use Python to convert gef and gem file formats? I remember there was a tutorial before, but I can't find it now. Can you provide me with this Python code or tutorial? And I have already installed Stereopy.Thank you！

**Comment by LyonLen** [comment]
We don't have methods to do conversion  between gem and gef .
Instead, you can follow the gefpy tutorials trying:
https://gefpy.readthedocs.io/en/latest/Examples.html
Hope these can help~

**Comment by Taoli0113** [comment]
Well, thank you very much！

**Comment by Taoli0113** [comment]
Thank you very much, this was very helpful to me, and now the problem has been solved!











在 2023-05-09 17:12:51，"LyonLen" ***@***.***> 写道：

We don't have methods to do conversion between gem and gef .
Instead, you can follow the gefpy tutorials trying:
https://gefpy.readthedocs.io/en/latest/Examples.html
Hope these can help~
