### ISSUE TITLE
tools

### ISSUE THREAD

**Issue by qiupinghust** [BGIResearch/stereopy#5]
- dim reduce
- [x] pca
- [x] umap
- [x] tsen
- [x] low variance
- [x] factor analysis

- clustering
- [x] leiden
- [x] louvain
- [x] phenograph

- cell type annotation
- [x] direct annotation using random forest

- gene pattern
- [ ] find pattern
- [ ] recode sparkx

- marker genes
- [x] t-test
- [x] wilcoxon-test
- [ ] spatial lag model

- enrich
- [ ] go enrich
- [ ] pathway activation

- RNA velocity

**Comment by wanruiwen-genomics-cn** [comment]
Dear @qiupinghust,

Thank you for maintaining this development tracking issue!

**Short answer:** This is an internal development roadmap listing tools to implement. Most checked items are now available in the codebase, while a few unchecked items (SPARKX, GO enrichment, pathway activation) remain unimplemented.

---

## Assessment
- **Type:** feature request (development tracker)
- **Severity:** low
- **Affected module:** `stereo/tools/`, `stereo/algorithm/`

## What Is Happening
This issue serves as a development checklist tracking the implementation status of various analysis tools in Stereopy. It was created early in the project to plan the tool development roadmap.

## Current Implementation Status

### Completed (checked items verified in codebase)
| Tool | Status | Module |
|------|--------|--------|
| PCA | Implemented | `stereo/algorithm/dim_reduce.py` |
| UMAP | Implemented | `stereo/algorithm/umap.py` |
| t-SNE | Implemented | `stereo/algorithm/dim_reduce.py` |
| Highly variable genes | Implemented | `stereo/algorithm/highly_variable_genes.py` |
| Leiden | Implemented | `stereo/algorithm/leiden.py` |
| Louvain | Implemented | `stereo/algorithm/_louvain.py` |
| Phenograph | Implemented | `stereo/algorithm/phenograph.py` |
| Cell type annotation (RF) | Implemented | `stereo/tools/cell_type_anno.py` |
| t-test markers | Implemented | `stereo/tools/find_markers.py` |
| Wilcoxon-test markers | Implemented | `stereo/algorithm/mannwhitneyu.py` |
| RNA velocity | Implemented | `stereo/tools/rna_velocity.py` |

### Unchecked items — current status
| Tool | Status | Notes |
|------|--------|-------|
| Find pattern | Partially addressed | `stereo/tools/spatial_pattern_score.py` exists |
| Recode SPARKX | Not found | No SPARKX implementation in codebase |
| Spatial lag model | Partially addressed | `stereo/tools/spatial_lag.py` exists |
| GO enrichment | Not found | No GO enrichment module in codebase |
| Pathway activation | Not found | No pathway activation module in codebase |

## Notes
- The majority of the planned tools have been successfully implemented.
- Three items (SPARKX, GO enrichment, pathway activation) appear to still be unimplemented as of the current codebase.
- The spatial pattern and spatial lag tools have partial implementations that may cover the originally intended functionality.
- Consider closing this issue if the remaining items are tracked elsewhere or no longer planned.

Please let us know if you have further questions!

Best regards,
Stereopy Maintainer

**Comment by wanruiwen-genomics-cn** [comment]
Dear @qiupinghust,

Thank you for maintaining this development tracking list!

**Short answer:** This issue serves as an internal roadmap for tool implementation and is not a bug report — no code changes are needed.

---

## Assessment
- **Type:** feature request (development tracking)
- **Severity:** low
- **Affected module:** `stereo/tools/`, `stereo/algorithm/`

## What Is Happening
This issue tracks the implementation status of various analysis tools in Stereopy, including dimensionality reduction (PCA, UMAP, t-SNE), clustering (Leiden, Louvain, Phenograph), marker gene detection, enrichment analysis, and RNA velocity. Several items are already checked off as completed.

## Current Status
Based on the checklist, the following items remain open:
- **Gene pattern:** find pattern, recode sparkx
- **Marker genes:** spatial lag model
- **Enrich:** GO enrich, pathway activation
- **RNA velocity** (partially tracked)

## Notes
- This is an internal development tracking issue, not a bug or user-reported problem.
- The completed items reflect significant progress across core analysis workflows.
- Remaining items (spatial lag model, GO enrichment, pathway activation) represent future feature work.

Please let us know if you have further questions!

Best regards,
Stereopy Maintainer
