### ISSUE TITLE
cannot upgrate gefpy from 0.1.0 to >=0.1.1

### ISSUE THREAD

**Issue by ChenddatHKU** [BGIResearch/stereopy#52]
Dear Sir/Madam,

I cloned Stereopy form https://github.com/BGIResearch/stereopy, then installed the required packed locally (pycharm). Default installation was gefpy 0.1.0, how system warned requirement for gefpy>=0.1.1. Failure is always reminded, no matter installed from pycharm or pin from the terminal.
Thus, may I ask do you have any suggestions for this issue?

Thanks so much!

**Comment by huangzhibo** [comment]
Previously resolved in gefpy project.
