### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by DMaspero** [BGIResearch/stereopy#53]
Dear authors,

I am trying to install stereopy using the pip install stereopy command.
Unfortunately, I am facing the following error: " FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt' "

Could you please help me to solve this issue?

Best regards,
Davide Maspero

**Comment by wuyiran55** [comment]
Hi Davide

     This problem may occur when installing version 0.2.3, but we have the latest version 0.2.4. So please try to install stereopy again. If you have any problems, please feel free to contact us.

Best
Yiran Wu

**Comment by Arinze-BioX** [comment]
Hello,
I don't think this has been resolved.
I am trying to install version 0.2.4 and I get the same error: 
"FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'"

Could you please help to resolve this?

Kindly,
Arinze.
