### ISSUE TITLE
Error with "import stereo"

### ISSUE THREAD

**Issue by hanluhhh** [BGIResearch/stereopy#58]
dear authors:
error occurs when i trying 'import stereo' in python3.8, here is the message:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "D:\Anaconda3\envs\python38\lib\site-packages\stereo\__init__.py", line 6, in <module>
>     from . import io
>   File "D:\Anaconda3\envs\python38\lib\site-packages\stereo\io\__init__.py", line 9, in <module>
>     from .reader import read_gef, read_gem, read_ann_h5ad, read_stereo_h5ad, anndata_to_stereo, stereo_to_anndata
>   File "D:\Anaconda3\envs\python38\lib\site-packages\stereo\io\reader.py", line 28, in <module>
>     from shapely.geometry import Point, MultiPoint
>   File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\shapely\geometry\__init__.py", line 4, in <module>
>     from .base import CAP_STYLE, JOIN_STYLE
>   File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\shapely\geometry\base.py", line 19, in <module>
>     from shapely.coords import CoordinateSequence
>   File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\shapely\coords.py", line 8, in <module>
>     from shapely.geos import lgeos
>   File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\shapely\geos.py", line 154, in <module>
>     _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
>   File "D:\Anaconda3\envs\python38\lib\ctypes\__init__.py", line 373, in __init__
>     self._handle = _dlopen(self._name, mode)
> FileNotFoundError: Could not find module 'D:\Anaconda3\envs\python38\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.

how can i fix it?
best wishes, thank you.
han

**Comment by junhouhui** [comment]
hi, you can dowload the geos_c.dll file and put this file into your conda environment (Library\bin) path. Aslo, we don't support window environment for now. 
[__64-geos_c.dll3.5.0.0.zip](https://github.com/BGIResearch/stereopy/files/8859806/__64-geos_c.dll3.5.0.0.zip)
.
