### ISSUE TITLE
Error: No matching distribution found for gefpy>=0.1.1

### ISSUE THREAD

**Issue by zhangnan0107** [BGIResearch/stereopy#59]
Hi there,

I just got an error when installing stereopy (version 0.2.4), it seems there is something wrong with the gefpy package, could you please help me out of this?

`ERROR: Could not find a version that satisfies the requirement gefpy>=0.1.1 (from stereopy) (from versions: none)`
`ERROR: No matching distribution found for gefpy>=0.1.1`

![image](https://user-images.githubusercontent.com/34366426/159609294-9586c1b7-2f57-424a-964e-55b8e067b99c.png)

**Comment by wuyiran55** [comment]
Hi, @zhangnan0107 

Stereopy and gefpy do not support python 3.9 version, so please use python 3.7 or python 3.8 and try to install stereopy again.

We will update our tutorial. Thank you so much!

**Comment by zhangnan0107** [comment]
Hi yiran,

Thanks for your reply. Tried python 3.8 and it worked. :)
