### ISSUE TITLE
Jinja2 version changed

### ISSUE THREAD

**Issue by magcurly** [BGIResearch/stereopy#63]
Please check for the renewal of Jinja2 package.
It's no longer able to import Markup from jinja2 since version 3.1.0. You can either renew the script or restrict the Jinja2 version in requirement.txt. Otherwise, importing stereo would fail.

Another suggestion, hope developers can create a conda environment.yaml for the ease of installation. If installing through pip, it would be a mess to install the large amount of dependent libraries. 

Sincerely,
magcurly

**Comment by wuyiran55** [comment]
hi, @magcurly
 
We have noticed the mistakes caused by Jinjia2 and we will offer the method for installation via conda.
Thank you so much for your advice.
