### ISSUE TITLE
Installation Issues: gefpy and requirements.txt

### ISSUE THREAD

**Issue by Arinze-BioX** [BGIResearch/stereopy#65]
Dear authors,
I am having difficulty installing the stereopy package.

When I run:
pip install stereopy==0.2.4
I get the error:
ERROR: Could not find a version that satisfies the requirement gefpy>=0.1.1 (from stereopy) (from versions: none)
ERROR: No matching distribution found for gefpy>=0.1.1

When I run:
pip install stereopy
I get the error:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

And it seems the package has heavy dependency, so it is hard to directly build it.

Could you please help me in understanding the problem and in getting around it?

Kind regards,
Arinze.

**Comment by ratbb** [comment]
i have the save problem ，i cant solve it

**Comment by junhouhui** [comment]
hi, may i ask what is your python version? We only support python3.7 and python3.8 now. And also we just support linux enviroment. We will update stereopy as soon as possible to solve the installation issues.

**Comment by PSSUN** [comment]
Hi @junhouhui ,
Any update here? We used Python 3.8 and met the same error:
<img width="1045" alt="aa922fb3d4f58cf1865e9c872c8f58e" src="https://user-images.githubusercontent.com/29281162/197782859-5a6f6139-0290-454e-8717-fdc333268e0d.png">

<img width="1150" alt="219cb9eba3b6b5866ee2ecf5ab400a5" src="https://user-images.githubusercontent.com/29281162/197782748-19d21107-d73f-478c-beb8-c312d436cc98.png">

System info:
![5333b35b61c78571f14f7ca5194beca](https://user-images.githubusercontent.com/29281162/197782610-c53d6351-4ca1-4a33-aefd-319f68c7be89.jpg)

**Comment by Arinze-BioX** [comment]
Hi PSUN, can you try specifically python 3.8.12? I think this worked for me.

**Comment by PSSUN** [comment]
Hi @Arinze-BioX ,
Thanks for this info, but it still does not work.

**Comment by Arinze-BioX** [comment]
Hi PSUN,
Can you elaborate on what you did? Did you use the following commands:
`conda create --name st python=3.8.12
conda activate st
pip install stereopy`

Also, have you considered manually downlading the requirements.txt file from here: https://github.com/BGIResearch/stereopy/blob/main/requirements.txt, and specifying this requirements.txt file when creating your st environment?

**Comment by PSSUN** [comment]
> Hi PSUN, Can you elaborate on what you did? Did you use the following commands: `conda create --name st python=3.8.12` `conda activate st` `pip install stereopy`
> 
> Also, have you considered manually downloading the requirements.txt file from here: https://github.com/BGIResearch/stereopy/blob/main/requirements.txt, ensure the requirements.txt file specifies python version 3.8.12, then specify this requirements.txt file when creating your st environment? For instance:
> 
> `conda create --name st --file /path-to/requirements.txt` `conda activate st` `pip install stereopy`

Thank you @Arinze-BioX 
I modified some of the versions, it works for me now : )

**Comment by junhouhui** [comment]
Notice: this issue has been closed because it has been inactive for 14 days. You may reopen this issue if it has been closed in error.
