### ISSUE TITLE
can not read tssue.gef

### ISSUE THREAD

**Issue by JingGuo1997** [BGIResearch/stereopy#72]
Hi authors:
when i read informations of tissue.gef, i got that error.

data_path = './SS200000385BR_E3.tissue.gef'
st.io.read_gef_info(data_path)

2022-07-04 11:11:09 Stereo 1068023 139744111322944 reader 576 INFO: This is BGEF file which contains traditional bin infomation.
2022-07-04 11:11:09 Stereo 1068023 139744111322944 reader 577 INFO: bin_type: bins
2022-07-04 11:11:09 Stereo 1068023 139744111322944 reader 580 INFO: Bin size list: ['bin1']
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-6adb0ae20150> in <module>
----> 1 st.io.read_gef_info(data_path)

/home/program/conda/anaconda3/envs/stereopy/lib/python3.8/site-packages/stereo/io/reader.py in read_gef_info(file_path)
    580         logger.info('Bin size list: {0}'.format(info_dict['bin_list']))
    581 
--> 582         info_dict['resolution'] = h5_file['geneExp']['bin1']['expression'].attrs['resolution'][0]
    583         logger.info('Resolution: {0}'.format(info_dict['resolution']))
    584 

IndexError: invalid index to scalar variable.

**Comment by junhouhui** [comment]
You can use 'read_gef_info' function to read SN.gef information.

**Comment by JingGuo1997** [comment]
Thanks. SN.gef can be read successfully

**Comment by junhouhui** [comment]
Stereopy can read information of tssue.gef in version 0.4.0
