### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by JenC9292** [BGIResearch/stereopy#76]
Hi, I am on a mac (2.3 GHz 8-Core Intel Core i9) and I am having a lot of trouble getting stereopy to work. Is there a docker container/conda environment which can be used to install stereopy? While it says it is installed, when I run several tools it says it requires further modules/packages, a lot of these having incompatibilities with the existing modules. Any streamlined installation methods would be greatly appreciated.

**Comment by junhouhuiBGI** [comment]
Hi, sorry to inform you that stereopy is currently only used in the linux environment，mac is not supported. We will provide conda environment as soon as possible.
