### ISSUE TITLE
Cell segmentation

### ISSUE THREAD

**Issue by JenC9292** [BGIResearch/stereopy#77]
Hi, I have run into errors for both cell segmentation methods. I have included the output. The tif input image is from ImageQC and did pass.

![image](https://user-images.githubusercontent.com/74996578/191252389-00434c62-ea23-4af0-b565-36d127566814.png)

**Comment by tanliwei-coder** [comment]
Please tell me which version of the stereopy you are using.

**Comment by tanliwei-coder** [comment]
I think you are using a very old version of stereopy, please upgrade to the latest version by runing **pip install --upgrade stereopy**

**Comment by JenC9292** [comment]
yes I think you are right. Will upgrade and try again!
