### ISSUE TITLE
How to use stereopy for registration of histological images and gene expression images

### ISSUE THREAD

**Issue by wenjiecai** [BGIResearch/stereopy#79]
Hello
Thanks for developing the stereopy. Recently, when I used stereopy for tissue segmentation (function: tissue_extraction_to_bgef), I found that the axolotl data on the official website of Huada spatiotemporal omics (https://db.cngb.org/stomics/artista/download.html) was not aligned with the genetic data. I checked the paper, mentioned that the author performed the alignment manually.  so I want to know if there is a way to align and complete the segmentation of the tissue through the stereopy package?

gene scatter plot:

<img width="1116" alt="axolotl_2DP_1_gene_scatter" src="https://user-images.githubusercontent.com/33197950/195364477-c81cdb96-4945-4f13-a782-36f63db62ca4.png">

image:
<img width="394" alt="axolotl_2DP_1_image" src="https://user-images.githubusercontent.com/33197950/195364632-3c438143-e864-4bc4-9eec-7e8fc5705d84.png">

tissue cut scatter plot:
<img width="1127" alt="axolotl_2DP_1_tissuecut_scatter" src="https://user-images.githubusercontent.com/33197950/195364876-f9c8cb2d-fe7d-4eee-b2a1-76ea865d95e3.png">

**Comment by qiqiHE93** [comment]
hi, could you tell me the download link of the image (sn.tif) mentioned here ? ( and also the gene expression matrix (gem.gz/gef)

**Comment by wenjiecai** [comment]
> 
link of image: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/2DPI_1.tif
gem file: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/2DPI_1.gem.gz

the spatiotemporal database link: https://db.cngb.org/stomics/artista/download.html

**Comment by TheSallyGardens** [comment]
> > 
> 
> link of image: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/2DPI_1.tif gem file: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/2DPI_1.gem.gz
> 
> the spatiotemporal database link: https://db.cngb.org/stomics/artista/download.html
Hi,you can follow the steps below to run.
First,You need to use imageQC1.0.8(https://github.com/BGIResearch/imageQC) to control your tif.
Second,Use SAW4.1.0(https://github.com/BGIResearch/SAW) to register images.
Finally, get the image from the registration result.
![image](https://user-images.githubusercontent.com/40382381/195786596-6e6dc131-ca7c-438c-80bc-2c96b85c341f.png)
link of image:https://pan.genomics.cn/ucdisk/s/2ey6F3

**Comment by wenjiecai** [comment]
> > > 
> > 
> > 
> > link of image: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/2DPI_1.tif gem file: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/2DPI_1.gem.gz
> > the spatiotemporal database link: https://db.cngb.org/stomics/artista/download.html
> > Hi,you can follow the steps below to run.
> > First,You need to use imageQC1.0.8(https://github.com/BGIResearch/imageQC) to control your tif.
> > Second,Use SAW4.1.0(https://github.com/BGIResearch/SAW) to register images.
> > Finally, get the image from the registration result.
> > ![image](https://user-images.githubusercontent.com/40382381/195786596-6e6dc131-ca7c-438c-80bc-2c96b85c341f.png)

Hi, I have install imageQC1.0.8, when I drag and drop the image files (2DPI_1.tif) into the program window, requested to fill in image parameters. I don't know where to get these parameters and the ChipNo. Should I use the default ExtraInfo parameters? 

![ImageQC](https://user-images.githubusercontent.com/33197950/195812014-7b034f90-5864-43a0-ad45-936041aa02bd.png)

**Comment by TheSallyGardens** [comment]
You can use this tif(https://pan.genomics.cn/ucdisk/s/2ey6F3) file directly in  stereopy.Please refer to the user manual for the use method of imageQC1.0.8.

**Comment by wenjiecai** [comment]
> You can use this tif(https://pan.genomics.cn/ucdisk/s/2ey6F3) file directly in stereopy.Please refer to the user manual for the use method of imageQC1.0.8.

hi, I am very grateful for your help. I want to research cell segmentation algorithm based image, so I also need to register other data of axolotl  dataset. 
Following your method, I have successfully registered the data of 2DPI slices by use default parameters of ImageQc. However, when registering other data, I encountered a new problem, that is, the image can pass imageQC, but an error occurs when using the SAW registration tool. 

example:
gem file link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/10DPI_1.gem.gz
image file link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/10DPI_1.tif

the error:
<img width="1680" alt="error" src="https://user-images.githubusercontent.com/33197950/195923109-04005054-1042-4598-a7c7-0b5f889f616d.png">

log:
[20221014-19-07-25.log](https://github.com/BGIResearch/stereopy/files/9789448/20221014-19-07-25.log)

**Comment by TheSallyGardens** [comment]
Please move to https://github.com/BGIResearch/SAW/issues/17
