### ISSUE TITLE
How to implement interactive scatter with jupyter.

### ISSUE THREAD

**Issue by ziongfen** [BGIResearch/stereopy#80]
I followed the example and ran the code on jupyter, but I did not get the Interactive scatter, How can I solve it? thanks.

**Comment by panjie-payne** [comment]
Could you please show us the code you ran or errors you got here?

**Comment by panjie-payne** [comment]
> I followed the example and ran the code on jupyter, but I did not get the Interactive scatter, How can I solve it? thanks.

Could you please show us the code you ran or errors you got here?

**Comment by ziongfen** [comment]
thanks,i wiil show the code as following.
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import stereo as st
path = '/share4/users/xiongfeng001/spatial/SS200000135TL_D1.tissue.gef'
st.io.read_gef_info(path)

data = st.io.reader.read_gef(path, bin_size=50)
data.tl.cal_qc()
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][618][INFO]: This is GEF file which contains traditional bin infomation.
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][619][INFO]: bin_type: bins
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][622][INFO]: Bin size list: ['bin1']
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][628][INFO]: Resolution: 500
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][631][INFO]: Gene count: 20816
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][640][INFO]: offsetX: 0
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][643][INFO]: offsetY: 2
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][646][INFO]: Width: 13441
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][649][INFO]: Height: 19774
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][652][INFO]: Max Exp: 14
[2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][518][INFO]: read_gef begin ...
[2022-10-21 13:28:49][Stereo][153970][140656984868672][reader][591][INFO]: the matrix has 35890 cells, and 20816 genes.
[2022-10-21 13:28:50][Stereo][153970][140656984868672][reader][599][INFO]: read_gef end.
[2022-10-21 13:28:50][Stereo][153970][140656984868672][st_pipeline][40][INFO]: start to run cal_qc...
[2022-10-21 13:28:50][Stereo][153970][140656984868672][st_pipeline][43][INFO]: cal_qc end, consume time 0.0602s.
data = st.io.read_gef(path, bin_size=40)
data.tl.cal_qc()
[2022-10-21 13:29:36][Stereo][153970][140656984868672][reader][518][INFO]: read_gef begin ...
[2022-10-21 13:29:39][Stereo][153970][140656984868672][reader][591][INFO]: the matrix has 55922 cells, and 20816 genes.
[2022-10-21 13:29:39][Stereo][153970][140656984868672][reader][599][INFO]: read_gef end.
[2022-10-21 13:29:39][Stereo][153970][140656984868672][st_pipeline][40][INFO]: start to run cal_qc...
[2022-10-21 13:29:39][Stereo][153970][140656984868672][st_pipeline][43][INFO]: cal_qc end, consume time 0.0730s.
ins = data.plt.interact_spatial_scatter(width=500, height=500,poly_select=False)
ins.show()
AttributeError                            Traceback (most recent call last)
File /share/software/apps/anaconda3_v2205/envs/spatial_trans/lib/python3.8/site-packages/IPython/core/formatters.py:973, in MimeBundleFormatter.__call__(self, obj, include, exclude)
    970     method = get_real_method(obj, self.print_method)
    972     if method is not None:
--> 973         return method(include=include, exclude=exclude)
    974     return None
    975 else:

File /share/software/apps/anaconda3_v2205/envs/spatial_trans/lib/python3.8/site-packages/panel/viewable.py:616, in Viewable._repr_mimebundle_(self, include, exclude)
    614 doc = _Document()
    615 comm = state._comm_manager.get_server_comm()
--> 616 model = self._render_model(doc, comm)
    617 ref = model.ref['id']
    618 manager = CommManager(comm_id=comm.id, plot_id=ref)

File /share/software/apps/anaconda3_v2205/envs/spatial_trans/lib/python3.8/site-packages/panel/viewable.py:465, in Renderable._render_model(self, doc, comm)
    458     embed_state(self, model, doc,
    459                 json=config.embed_json,
    460                 json_prefix=config.embed_json_prefix,
    461                 save_path=config.embed_save_path,
    462                 load_path=config.embed_load_path,
    463                 progress=False)
    464 else:
--> 465     add_to_doc(model, doc)
    466 return model

File /share/software/apps/anaconda3_v2205/envs/spatial_trans/lib/python3.8/site-packages/panel/io/model.py:57, in add_to_doc(obj, doc, hold)
     55 remove_root(obj)
     56 doc.add_root(obj)
---> 57 if doc._hold is None and hold:
     58     doc.hold()

AttributeError: 'Document' object has no attribute '_hold'

**Comment by panjie-payne** [comment]
> 



> thanks,i wiil show the code as following.
> 
> ```ruby
> %matplotlib inline
> import warnings
> warnings.filterwarnings('ignore')
> import stereo as st
> path = '/share4/users/xiongfeng001/spatial/SS200000135TL_D1.tissue.gef
> st.io.read_gef_info(path)
> data = st.io.reader.read_gef(path, bin_size=50)
> data.tl.cal_qc()
> ```
> 
> [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][618][INFO]: This is GEF file which contains traditional bin infomation. [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][619][INFO]: bin_type: bins [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][622][INFO]: Bin size list: ['bin1'] [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][628][INFO]: Resolution: 500 [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][631][INFO]: Gene count: 20816 [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][640][INFO]: offsetX: 0 [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][643][INFO]: offsetY: 2 [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][646][INFO]: Width: 13441 [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][649][INFO]: Height: 19774 [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][652][INFO]: Max Exp: 14 [2022-10-21 13:28:46][Stereo][153970][140656984868672][reader][518][INFO]: read_gef begin ... [2022-10-21 13:28:49][Stereo][153970][140656984868672][reader][591][INFO]: the matrix has 35890 cells, and 20816 genes. [2022-10-21 13:28:50][Stereo][153970][140656984868672][reader][599][INFO]: read_gef end. [2022-10-21 13:28:50][Stereo][153970][140656984868672][st_pipeline][40][INFO]: start to run cal_qc... [2022-10-21 13:28:50][Stereo][153970][140656984868672][st_pipeline][43][INFO]: cal_qc end, consume time 0.0602s.
> 
> ```ruby
> data = st.io.read_gef(path, bin_size=40)
> data.tl.cal_qc()
> ```
> 
> [2022-10-21 13:29:36][Stereo][153970][140656984868672][reader][518][INFO]: read_gef begin ... [2022-10-21 13:29:39][Stereo][153970][140656984868672][reader][591][INFO]: the matrix has 55922 cells, and 20816 genes. [2022-10-21 13:29:39][Stereo][153970][140656984868672][reader][599][INFO]: read_gef end. [2022-10-21 13:29:39][Stereo][153970][140656984868672][st_pipeline][40][INFO]: start to run cal_qc... [2022-10-21 13:29:39][Stereo][153970][140656984868672][st_pipeline][43][INFO]: cal_qc end, consume time 0.0730s.
> 
> ```ruby
> ins = data.plt.interact_spatial_scatter(width=500, height=500,poly_select=False)
> ins.show()
> ```
> 
> AttributeError Traceback (most recent call last) File /share/software/apps/anaconda3_v2205/envs/spatial_trans/lib/python3.8/site-packages/IPython/core/formatters.py:973, in MimeBundleFormatter.**call**(self, obj, include, exclude) 970 method = get_real_method(obj, self.print_method) 972 if method is not None: --> 973 return method(include=include, exclude=exclude) 974 return None 975 else:
> 
> File /share/software/apps/anaconda3_v2205/envs/spatial_trans/lib/python3.8/site-packages/panel/viewable.py:616, in Viewable._repr_mimebundle_(self, include, exclude) 614 doc = _Document() 615 comm = state._comm_manager.get_server_comm() --> 616 model = self._render_model(doc, comm) 617 ref = model.ref['id'] 618 manager = CommManager(comm_id=comm.id, plot_id=ref)
> 
> File /share/software/apps/anaconda3_v2205/envs/spatial_trans/lib/python3.8/site-packages/panel/viewable.py:465, in Renderable._render_model(self, doc, comm) 458 embed_state(self, model, doc, 459 json=config.embed_json, 460 json_prefix=config.embed_json_prefix, 461 save_path=config.embed_save_path, 462 load_path=config.embed_load_path, 463 progress=False) 464 else: --> 465 add_to_doc(model, doc) 466 return model
> 
> File /share/software/apps/anaconda3_v2205/envs/spatial_trans/lib/python3.8/site-packages/panel/io/model.py:57, in add_to_doc(obj, doc, hold) 55 remove_root(obj) 56 doc.add_root(obj) ---> 57 if doc._hold is None and hold: 58 doc.hold()
> 
> AttributeError: 'Document' object has no attribute '_hold'

Hi, 
   just ran agin your code and no exception threw.  I checked errors above, maybe the problem lay with the version of panel and holoviews, maybe you can reinstall referred libraries and have a try again.   If possible, pelase create a new conda environment and install libraries we mentioned in requirements.txt

**Comment by junhouhui** [comment]
Notice: this issue has been closed because it has been inactive for 14 days. You may reopen this issue if it has been closed in error.
