### ISSUE TITLE
What does cellId stand for in the .gem file?

### ISSUE THREAD

**Issue by PSSUN** [BGIResearch/stereopy#82]
Hi,
In the document, the explanation for x, and y is:
> x, y are the spatial position of the gene in the tissue section.

And the explanation for .gem file looks like is:

GeneID | x | y | count
-- | -- | -- | --
Gene1 | 121 | 200 | 2
Gene2 | 234 | 300 | 1
… | … | … | …
Gene n | 234 | 300 | 1

When I load the file **SS200000135TL_D1.tissue.gem**, I can see the table like this:

geneID | x | y | MIDCount | ExonCount | CellID
-- | -- | -- | -- | -- | --
Camk1d | 7566 | 19777 | 1 | 0 | 56203
Gabra1 | 7567 | 19777 | 1 | 1 | 56203

The x values of Camk1d and Gabra1 are different(756**6** / 756**7**), but they have the same cell id: **56203**. So I got two questions here:
1. What's the exact meaning of x, and y here, do they represent the DNB barcode position? Or do they have other means? 
2. I didn't find the explanation for cols **CellID** here, could you please tell me what it means here?

Thank you!

**Comment by qiqiHE93** [comment]
hi PSSUN

it's nice to see someone are poring over our tutorial~

Firstly we have 2 types of gene expression result files, but all in h5 file format : the square bin result files (SN.gef/SN.gem), the cell bin result files (cellbin.gef/cellbin.gem)

And the structure of the square bin result files (SN.gef/SN.gem) is already updated~ 
the column names in the old one (general from saw_v4) is "geneID  x       y       MIDCount        ExonCount", indicating “annotated_gene_ID ; coordinate_x_in_chip ; coordinate_y_in_chip ; MID_count”; 
but in the new, we added a new column so the header is like  "geneID  x       y       MIDCount        ExonCount"

And the structure of the cell bin result file (SN.cellbin.gef/SN.cellbin.gem) is the example you posted in your question~
the columns name is "geneID  x       y       MIDCount        ExonCount       CellID"

![image](https://user-images.githubusercontent.com/44603057/200218065-574a19b7-4189-4476-82c7-64d1900ec196.png)

FAQ
Q: What's the exact meaning of x, and y here, do they represent the DNB barcode position? Or do they have other means?
A: yes~ the physical location (CID, dnb coordination)  

Q: I didn't find the explanation for cols CellID here, could you please tell me what it means here?
A: cellID is made by an ordered list, referred to by index Numbers

**Comment by qiqiHE93** [comment]
<img width="555" alt="微信图片_20221107111355" src="https://user-images.githubusercontent.com/44603057/200218928-c9829cd8-932b-4aa2-863d-19d45b70e963.png">

**Comment by PSSUN** [comment]
Hi @qiqiHE93,

Thank you for your explanation. One more question,

> A: here we name every **cell** detected by our software using a number.

I review the code in **stereo.io.reader.read_gem** (line 63):

```python
cells = df['cell_id'].unique()
genes = df['geneID'].unique()
cells_dict = dict(zip(cells, range(0, len(cells))))
genes_dict = dict(zip(genes, range(0, len(genes))))
rows = df['cell_id'].map(cells_dict)
cols = df['geneID'].map(genes_dict)
logger.info(f'the martrix has {len(cells)} cells, and {len(genes)} genes.')
exp_matrix = csr_matrix((df['UMICount'], (rows, cols)), shape=(cells.shape[0], genes.shape[0]), dtype=np.int32)
```

So the **cell** here represents the biological cell in tissue. Because it was used in exp_matrix to build the relationship between cells and genes. Meanwhile, it means we have identified each cell with its location from the upstream analysis such as SAW, stereopy do the downstream analysis  such as [Cell correction](https://stereopy.readthedocs.io/en/latest/Tutorials/cell_correction.html) et al. right?

Thank you!

**Comment by qiqiHE93** [comment]
“we have identified each cell with its location from the upstream analysis such as SAW, stereopy do the downstream analysis such as [Cell correction](https://stereopy.readthedocs.io/en/latest/Tutorials/cell_correction.html) et al. right?”

Generally, we generate the gene expression matrix including the identified cell information and gene information in the cellCut step (whether in SAW or Stereopy). 
But in the cellCorrection step, the cell with a small amount of genes may be removed. 
So if you compare the two cellbin.gef (after cellCorrection and after cellCut), maybe the cell index are different for the same cell.

**Comment by PSSUN** [comment]
Thank you!
