### ISSUE TITLE
Fatal error at src/core/vector.c:483 : Assertion failed: v->stor_begin != NULL

### ISSUE THREAD

**Issue by lljzz** [BGIResearch/stereopy#83]
When I run the "dyn.tl.leiden(adata, result_key='spatial_leiden_res')", an error is reported:
“Fatal error at src/core/vector.c:483 : Assertion failed: v->stor_begin != NULL ”
and the Jupyter will appears to have died.
Is there any methods to solve it ? thx.

**Comment by junhouhuiBGI** [comment]
Hi, Can you provide the analysis process steps and data? Or print adata before executing the dyn.tl.leiden step, thanks!

**Comment by lljzz** [comment]
Thanks Reply.I reproduced the problem today.
You can check my Jupyter file. 
And I  use the "dyn.tl.louvain(adata, result_key='spatial_louvain_res')" ,it worked. Then I found another problem: I can't save ".h5ad" file. The problem is below:

`NotImplementedError: Failed to write value for uns/velocyto_SVR/SVR, since a writer for type <class 'method'> has not been implemented yet.
<img width="613" alt="test error" src="https://user-images.githubusercontent.com/117802608/201288547-e29c3589-b774-4be7-b129-7f7822faafdb.png">


Above error raised while writing key 'uns/velocyto_SVR/SVR' of <class 'h5py._hl.files.File'> from /.`
<img width="613" alt="test error" src="https://user-images.githubusercontent.com/117802608/201288925-cc82ca02-e834-4f6c-b703-12444eec2857.png">
[test1_23.zip](https://github.com/BGIResearch/stereopy/files/9988059/test1_23.zip)

**Comment by junhouhuiBGI** [comment]
Hi, this is because anndata cannot support writing of <class 'method'>. This needs to be adapted or adjusted by anndata or dynamo. If you need to save, you can delete these two results in adata first. 
del adata.uns['velocyto_SVR']
del adata.uns['umap_fit']
After that, you can save your result to h5ad file.(adata.write_h5ad())

**Comment by lljzz** [comment]
ok, Thank you, I got it. 
Then,But i still want to know that why i ran "dyn.tl.leiden" failed. 3Q.

**Comment by junhouhuiBGI** [comment]
Sorry, I can't reproduce your problem with our data.
I found related problems (https://github.com/igraph/igraph/issues/1356), but I can't locate the specific cause, which may be related to the data. This requires studying dynamo's Leiden algorithm and the corresponding data to reproduce this problem.

**Comment by lljzz** [comment]
OK. Thanks a lot.
