### ISSUE TITLE
Error running `annh5ad2rds.R`

### ISSUE THREAD

**Issue by shaniAmare** [BGIResearch/stereopy#85]
Hi to the developers,

Thank you very much for the thoughtful `.h5ad` to `Seurat` conversion `R` script.I tried using that on the data I downloaded form the STOMICS database, however I ran into a problem.

Here is the code I ran and the error ( I ran this with `R/4.2`)

```
sama0023@arxcss:~/STOMICS$ Rscript annh5ad2rds.R --infile ./Stomics_data/E16.5_E2S3.MOSTA.h5ad --outfile ./Stomics_data/E16.5_E2S3.MOSTA.RDS
Registered S3 method overwritten by 'SeuratDisk':
  method            from  
  as.sparse.H5Group Seurat
Attaching SeuratObject

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "Converting h5ad to h5seurat file."
Warning: Unknown file type: h5ad
Creating h5Seurat file for version 3.1.5.9900
Adding X as data
Adding X as counts
Adding meta.features from var
Adding spatial as cell embeddings for spatial
Warning: Cannot find a reduction named pca (PCs in varm)
Adding annotation_colors to miscellaneous data
Adding layer count as data in assay count
Adding layer count as counts in assay count
[1] "Loading h5seurat file."
Validating h5Seurat file
Initializing Spatial with data
Adding counts for Spatial
Adding feature-level metadata for Spatial
Initializing count with data
Adding counts for count
Adding reduction spatial
Adding cell embeddings for spatial
Adding miscellaneous information for spatial
Adding command information
Adding cell-level metadata
Warning: Invalid name supplied, making object name syntactically valid. New object name is n_genes_by_countslog1p_n_genes_by_countstotal_countslog1p_total_countsannotationRegulon...Acaa1aRegulon...AhrRegulon...Alx1Regulon...Alx4Regulon...Arid3aRegulon...ArntRegulon...Arnt2Regulon...ArxRegulon...Atf2Regulon...Atf3Regulon...Atf4Regulon...Atf6Regulon...Bach2Regulon...Barhl1Regulon...Barhl2Regulon...Bcl6Regulon...Bcl6bRegulon...Bclaf1Regulon...Bhlhe22Regulon...Bhlhe40Regulon...Bhlhe41Regulon...BmycRegulon...Borcs8Regulon...BptfRegulon...Brf1Regulon...CebpaRegulon...CebpbRegulon...CebpdRegulon...CebpgRegulon...CebpzRegulon...Chd1Regulon...CicRegulon...ClockRegulon...Cnot3Regulon...Creb1Regulon...Creb3Regulon...Creb3l1Regulon...Creb3l2Regulon...CrxRegulon...CtcfRegulon...Cux1Regulon...Cux2Regulon...DbpRegulon...Dbx1Regulon...Ddit3Regulon...Ddx4Regulon...Dlx1Regulon...Dlx2Regulon...Dlx3Regulon...Dlx5Regulon...Dlx6Regulon...Dmrt2Regulon...E2f1Regulon...E2f2Regulon...E2f3Regulon...E2f4Regulon...E2f5Regu [... truncated]
Adding miscellaneous information
Adding tool-specific results
Warning message:
Cannot add objects with duplicate keys (offending key: spatial_), setting key to 'spatialla_' 
Error in `[.data.frame`(Stdata@meta.data, , c("x", "y")) : 
  undefined columns selected
Calls: unique -> [ -> [.data.frame
Execution halted
```

Can you please explain how this can be corrected?

Many thanks in advance,
Shani.

**Comment by shaniAmare** [comment]
I did a but of digging and the error is due to failing of line:
`cell_coords=unique(Stdata@meta.data[, c('x', 'y')])`

As there are no x and y coordinates in `meta.data`.

How can I fix that? Is there an external location I could retrieve this information from?

Many thanks,
Shani.

**Comment by junhouhuiBGI** [comment]
Hi, thanks for your question,  please wait a moment, we will study it.

**Comment by shaniAmare** [comment]
Thanks for the reply @junhouhuiBGI .

Can I then maybe get access to the corresponding data that is suitable to be processed by this approach? Thanks.

**Comment by raman91** [comment]
Hi, i also ran the script for converting anndata to seurat object for visium data, but i get a error message: Error in if (!x[[i]]$dims) { : the condition has length > 1. May i know how i solve this issue? Thank you

**Comment by LyonLen** [comment]
> Hi to the developers,
> 
> Thank you very much for the thoughtful `.h5ad` to `Seurat` conversion `R` script.I tried using that on the data I downloaded form the STOMICS database, however I ran into a problem.
> 
> Here is the code I ran and the error ( I ran this with `R/4.2`)
> 
> ```
> sama0023@arxcss:~/STOMICS$ Rscript annh5ad2rds.R --infile ./Stomics_data/E16.5_E2S3.MOSTA.h5ad --outfile ./Stomics_data/E16.5_E2S3.MOSTA.RDS
> Registered S3 method overwritten by 'SeuratDisk':
>   method            from  
>   as.sparse.H5Group Seurat
> Attaching SeuratObject
> 
> Attaching package: ‘dplyr’
> 
> The following objects are masked from ‘package:stats’:
> 
>     filter, lag
> 
> The following objects are masked from ‘package:base’:
> 
>     intersect, setdiff, setequal, union
> 
> [1] "Converting h5ad to h5seurat file."
> Warning: Unknown file type: h5ad
> Creating h5Seurat file for version 3.1.5.9900
> Adding X as data
> Adding X as counts
> Adding meta.features from var
> Adding spatial as cell embeddings for spatial
> Warning: Cannot find a reduction named pca (PCs in varm)
> Adding annotation_colors to miscellaneous data
> Adding layer count as data in assay count
> Adding layer count as counts in assay count
> [1] "Loading h5seurat file."
> Validating h5Seurat file
> Initializing Spatial with data
> Adding counts for Spatial
> Adding feature-level metadata for Spatial
> Initializing count with data
> Adding counts for count
> Adding reduction spatial
> Adding cell embeddings for spatial
> Adding miscellaneous information for spatial
> Adding command information
> Adding cell-level metadata
> Warning: Invalid name supplied, making object name syntactically valid. New object name is n_genes_by_countslog1p_n_genes_by_countstotal_countslog1p_total_countsannotationRegulon...Acaa1aRegulon...AhrRegulon...Alx1Regulon...Alx4Regulon...Arid3aRegulon...ArntRegulon...Arnt2Regulon...ArxRegulon...Atf2Regulon...Atf3Regulon...Atf4Regulon...Atf6Regulon...Bach2Regulon...Barhl1Regulon...Barhl2Regulon...Bcl6Regulon...Bcl6bRegulon...Bclaf1Regulon...Bhlhe22Regulon...Bhlhe40Regulon...Bhlhe41Regulon...BmycRegulon...Borcs8Regulon...BptfRegulon...Brf1Regulon...CebpaRegulon...CebpbRegulon...CebpdRegulon...CebpgRegulon...CebpzRegulon...Chd1Regulon...CicRegulon...ClockRegulon...Cnot3Regulon...Creb1Regulon...Creb3Regulon...Creb3l1Regulon...Creb3l2Regulon...CrxRegulon...CtcfRegulon...Cux1Regulon...Cux2Regulon...DbpRegulon...Dbx1Regulon...Ddit3Regulon...Ddx4Regulon...Dlx1Regulon...Dlx2Regulon...Dlx3Regulon...Dlx5Regulon...Dlx6Regulon...Dmrt2Regulon...E2f1Regulon...E2f2Regulon...E2f3Regulon...E2f4Regulon...E2f5Regu [... truncated]
> Adding miscellaneous information
> Adding tool-specific results
> Warning message:
> Cannot add objects with duplicate keys (offending key: spatial_), setting key to 'spatialla_' 
> Error in `[.data.frame`(Stdata@meta.data, , c("x", "y")) : 
>   undefined columns selected
> Calls: unique -> [ -> [.data.frame
> Execution halted
> ```
> 
> Can you please explain how this can be corrected?
> 
> Many thanks in advance, Shani.

Hi, I have read your description of annh5ad2rds.R's error running.
You can run these python codes before you run the convert script:
```python
import anndata
import numpy as np
import pandas as pd

ann_data = anndata.read('../demo_data/E16.5_E2S3.MOSTA.h5ad')
arr = np.array(ann_data.obs.index.str.split('_').to_list(), dtype=np.uint32)
ann_data.obs['x'] = pd.Series(arr[:, 0], index=ann_data.obs.index)
ann_data.obs['y'] = pd.Series(arr[:, 1], index=ann_data.obs.index)
ann_data.write_h5ad('../demo_data/E16.5_E2S3.MOSTA.test.h5ad')
```
May these can help you solve the problem. 
Wait for your reply~

**Comment by LyonLen** [comment]
> 

Hi, could you show me the data or how to get the data you use if it's unclassified？

**Comment by LyonLen** [comment]
> Hi, i also ran the script for converting anndata to seurat object for visium data, but i get a error message: Error in if (!x[[i]]$dims) { : the condition has length > 1. May i know how i solve this issue? Thank you

Hi, could you show me the data or how to get the data you use if it's unclassified？

**Comment by LyonLen** [comment]
This issue has been closed because it has been inactive for 14 days. 
You may reopen this issue if it has been closed in error.
Thx for your report.
