### ISSUE TITLE
How to add scale bar to cluster_scatter plot?

### ISSUE THREAD

**Issue by LixinyuLiu** [BGIResearch/stereopy#86]
Following the example code, I am wondering if it is possible to add a scale bar to the cluter scatter visualisation. Many thanks.

**Comment by junhouhuiBGI** [comment]
Sorry, we can't add a scale bar at this time, but will add it soon

**Comment by junhouhui** [comment]
Notice: this issue has been closed because it has been inactive for 14 days. You may reopen this issue if it has been closed in error.
