### ISSUE TITLE
Can't install stereopy developer's version

### ISSUE THREAD

**Issue by vladimirkovacevic** [BGIResearch/stereopy#87]
After creating conda environment I'm getting an error when I run setup:
```
Processing dependencies for stereopy==0.7.0
Searching for gefpy>=0.6.7
Reading https://pypi.org/simple/gefpy/
No local packages or working download links found for gefpy>=0.6.7
error: Could not find suitable distribution for Requirement.parse('gefpy>=0.6.7')
```
I suppose it could be solved by providing a specific Conda repository where all specified package versions are available.

**Comment by junhouhuiBGI** [comment]
Hello, is your installation environment linux? gefpy currently does not support windows and mac versions

**Comment by vladimirkovacevic** [comment]
@junhouhuiBGI OK, I see. Is there a workaround for this issue? What I see is that gefpy is a wrapper for [geftools](https://github.com/BGIResearch/geftools). I suppose geftools also work only on Linux, right? 
If there is no other way can you consider offering users a Docker image that would include the entire environment and a "docker run command" to run Jupyter notebook from it?

**Comment by junhouhuiBGI** [comment]
Hello, gefpy itself is used in linux. We are generating a docker image, please wait a moment

**Comment by junhouhuiBGI** [comment]
Hello, you can download the docker image of stereopy through the link below.
[stereopy_docker_image](https://pan.genomics.cn/ucdisk/s/IfyIVj)

**Comment by vladimirkovacevic** [comment]
Thank you very much @junhouhuiBGI. It would be wonderful if you could push the image to [Dockerhub](https://hub.docker.com/), so the users could pull it with docker pull command. Also, I started downloading TAR that you send and it says it would take a day. So, for example, I don't know if BGI Research has an account on dockerhub, so if you create a new account there named bgi-research and name the docker with stereopy:1.0 then users might just type:
```
docker run -p 8888:8888 -it bgi-research/stereopy:1.0 /bin/bash -c "jupyter lab --JupyterApp.config_file='/home/stereonote/jupyter_notebook_config.py' --allow-root --ip=0.0.0.0 --NotebookApp.passwd=''"
```
The image will be pulled and after it, the Jupyter notebook on it should run.

**Comment by vladimirkovacevic** [comment]
@junhouhuiBGI just to check, have you managed to push the image to Dockerhub? Please tell me if I can help.

**Comment by junhouhuiBGI** [comment]
hi，we already push the image to Dockerhub, please visit [stereopy_docker](https://hub.docker.com/repository/docker/stomics/stereopy)

**Comment by vladimirkovacevic** [comment]
Thanks @junhouhuiBGI. I managed to pull it and to start Jupyter. Unfortunately, it cannot locate my browser:
```
Jupyter Server 1.23.3 is running at:
[I 2022-12-06 10:09:00.361 ServerApp] http://localhost:8888/lab?token=ad7a3afdc76c0bfed2f01e1efb06e784213c57ece3a85735
[I 2022-12-06 10:09:00.361 ServerApp]  or http://127.0.0.1:8888/lab?token=ad7a3afdc76c0bfed2f01e1efb06e784213c57ece3a85735
[I 2022-12-06 10:09:00.362 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-12-06 10:09:00.381 ServerApp] No web browser found: could not locate runnable browser.
```
I assume the reason for it lies in the [configuration](https://stackoverflow.com/questions/55554351/no-web-browser-found-could-not-locate-runnable-browser-jupyter-notebook) of Jupyter notebook. Do you have any suggestion on how to resolve this issue?

**Comment by junhouhuiBGI** [comment]
hi, please ignore this error, after starting docker, enter the url(http://127.0.0.1:8888/lab?token=ad7a3afdc76c0bfed2f01e1efb06e784213c57ece3a85735) directly in the browser. Then you can use jupyterlab, which contains stereopy
![1670394491087](https://user-images.githubusercontent.com/113407878/206105051-d831f342-e90e-4ab8-9041-6b91b1b96861.png)

**Comment by vladimirkovacevic** [comment]
@junhouhuiBGI yes, I've tried that also, but I'm getting in the browser: 
404 : Not Found
You are requesting a page that does not exist!

**Comment by panjie-payne** [comment]
> @junhouhuiBGI yes, I've tried that also, but I'm getting in the browser: 404 : Not Found You are requesting a page that does not exist!

Could you please check if this warning printed when docker run our image
WARNING: IPv4 forwarding is disabled. Networking will not work.

if printed, please check below:
1. vim /etc/sysctl.conf
2. add this row: net.ipv4.ip_forward=1
3. restart network: systemctl restart network
4. check if change effected: sysctl net.ipv4.ip_forward
if net.ipv4.ip_forward = 1 returnedm done

And for quite sure, restart docker is extremely recommended.
Hope this is useful for you, and contact us if any issue, will reply asap

**Comment by vladimirkovacevic** [comment]
@panjie-payne @junhouhuiBGI ,
no, I don't have this message printer. When I run the image:
```
docker run -p 8888:8888 -it stomics/stereopy:1.0.0 /bin/bash -c "jupyter lab --JupyterApp.config_file='/home/stereonote/jupyter_notebook_config.py' --allow-root --ip=0.0.0.0"
```
I'm getting: 
```
Traceback (most recent call last):
      File "/opt/software/python/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 355, in load_extension
        extension.load_all_points(self.serverapp)
      File "/opt/software/python/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 229, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/software/python/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 229, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/software/python/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 222, in load_point
        return point.load(serverapp)
      File "/opt/software/python/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 148, in load
        return loader(serverapp)
      File "/opt/software/python/lib/python3.8/site-packages/nbresuse/__init__.py", line 49, in load_jupyter_server_extension
        PrometheusHandler(PSUtilMetricsLoader(nbapp)), 1000
      File "/opt/software/python/lib/python3.8/site-packages/nbresuse/prometheus.py", line 25, in __init__
        gauge = Gauge(phrase, "counter for " + phrase.replace("_", " "), [])
      File "/opt/software/python/lib/python3.8/site-packages/prometheus_client/metrics.py", line 365, in __init__
        super().__init__(
      File "/opt/software/python/lib/python3.8/site-packages/prometheus_client/metrics.py", line 143, in __init__
        registry.register(self)
      File "/opt/software/python/lib/python3.8/site-packages/prometheus_client/registry.py", line 43, in register
        raise ValueError(
    ValueError: Duplicated timeseries in CollectorRegistry: {'total_memory_usage'}
```

**Comment by junhouhuiBGI** [comment]
We will also have the same error as you, but it will not affect the subsequent use of docker. Enter the url in the red box in the browser to use
![1670493348211](https://user-images.githubusercontent.com/113407878/206416740-10d67506-0fea-44bd-b568-d7e41f6d986b.png)

**Comment by vladimirkovacevic** [comment]
Yes, I've tried that, still getting 404 error :(

**Comment by junhouhuiBGI** [comment]
We can't reproduce your problem, we found someone else to test our image, but there is no 404 situation. Give us some time, we will find a few more people to test and see if we can reproduce your situation

**Comment by vladimirkovacevic** [comment]
@junhouhuiBGI It is working now! :)
I had another jupyter notebook server running locally, and there was probably a port collision. When I closed them and started it again it worked! Thank you very much for the assistance. Your help is greatly appreciated! I'm closing the issue.
