### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by vladimirkovacevic** [BGIResearch/stereopy#88]
Quick start notebook is requesting data:
```
# read the GEF file
mouse_data_path = './stereomics.h5'
```
But, on the provided [link](https://pan.genomics.cn/ucdisk/s/BvIrye) in the notebook, this file is not present. Also, the page is in Chinese, and it is impossible without a translation tool to guess which button is for download.

**Comment by junhouhuiBGI** [comment]
![1669616348768](https://user-images.githubusercontent.com/113407878/204207406-6ef59fbb-ee3c-4455-bb8c-6ddfce581fa0.png)
Hi, The stereomics.h5 file is equivalent to SS200000135TL_D1.tissue.gef. According to the red box in the picture, click the download button to download.

**Comment by vladimirkovacevic** [comment]
@junhouhuiBGI thank you for the prompt response. To improve user experience, could you please rename that file in Sharepoint or the notebook so they match? It would be great to add the link in the notebook to download it directly. Also, can this practice be applied to all other files? I think our future users would highly appreciate this.

**Comment by junhouhuiBGI** [comment]
Thank you very much for your suggestion, we will modify it according to your suggestion.

**Comment by LWA1008** [comment]
> ![1669616348768](https://user-images.githubusercontent.com/113407878/204207406-6ef59fbb-ee3c-4455-bb8c-6ddfce581fa0.png) Hi, The stereomics.h5 file is equivalent to SS200000135TL_D1.tissue.gef. According to the red box in the picture, click the download button to download.

where can I  download this demo data? thanks

**Comment by WeipengMO** [comment]
> ![1669616348768](https://user-images.githubusercontent.com/113407878/204207406-6ef59fbb-ee3c-4455-bb8c-6ddfce581fa0.png) Hi, The stereomics.h5 file is equivalent to SS200000135TL_D1.tissue.gef. According to the red box in the picture, click the download button to download.

Hi @junhouhuiBGI , when I clicked the download bottom, it returned error code, and could not download the data. Could you tell me how to solve ti? Thank you very much!

```
{
    "body": {
        "bean": null,
        "custom": {},
        "pageNumber": 0,
        "pageSize": 0,
        "rows": [],
        "total": 0
    },
    "clientId": "",
    "code": 400,
    "msg": "exception_in_readAndWrite_file",
    "notes": ""
}
```
